#!/usr/bin/env bash

# Setup git configuration for the user
#
# Run as the user to configure
#
# Requires:
# * $GIT_USER_NAME
# * $GIT_USER_EMAIL

if [[ $EUID -ne 0 ]]; then
  echo "ERROR: This script must be run as root" 1>&2
  exit 1
fi

if [[ "${GIT_USER_NAME}X" == "X" ]]; then
  echo 'ERROR please provide $GIT_USER_NAME'
  exit 1
fi
if [[ "${GIT_USER_EMAIL}X" == "X" ]]; then
  echo 'ERROR please provide $GIT_USER_EMAIL'
  exit 1
fi

cd ~vcap
chpst -u vcap:vcap git config -f ~vcap/.gitconfig user.name "${GIT_USER_NAME}"
chpst -u vcap:vcap git config -f ~vcap/.gitconfig user.email "${GIT_USER_EMAIL}"