#!/usr/bin/env bash

# Setup git configuration for the user
#
# Run as the user to configure
#
# Requires:
# * $GIT_USER_NAME
# * $GIT_USER_EMAIL

set -e # exit immediately if a simple command exits with a non-zero status

if [[ "${GIT_USER_NAME}X" == "X" ]]; then
  echo 'ERROR please provide $GIT_USER_NAME'
  exit 1
fi
if [[ "${GIT_USER_EMAIL}X" == "X" ]]; then
  echo 'ERROR please provide $GIT_USER_EMAIL'
  exit 1
fi

cd ~
git config -f .gitconfig user.name "${GIT_USER_NAME}"
git config -f .gitconfig user.email "${GIT_USER_EMAIL}"
git config -f .gitconfig color.ui true