#!/usr/bin/env bash

# Convert $PASSWORD into a salted password
# and return via STDOUT
#
# Requires:
# * $PASSWORD

set -e # exit immediately if a simple command exits with a non-zero status

mkpasswd -m sha-512 $PASSWORD
