#!/usr/bin/env bash

# Create vcap user & public keys
# Re-use new public keys for root user
#
# Requires:
# * $ORIGUSER - another local user with authorized_keys for SSH access; will be copied to vcap user

if [[ $EUID -ne 0 ]]; then
  echo "ERROR: This script must be run as root" 1>&2
  exit 1
fi

groupadd vcap
useradd vcap -m --shell /bin/bash -g vcap
mkdir -p /home/vcap/.ssh
chown -R vcap:vcap /home/vcap/.ssh
chmod 700 /home/vcap/.ssh

if [[ -f /home/vcap/.ssh/id_rsa ]]
then
  echo "public keys for vcap already exist, skipping..."
else
  echo "creating public keys for vcap/root user..."
  su -c "ssh-keygen -f ~/.ssh/id_rsa -N ''" vcap
fi

# Include same public keys for root user
echo "copy vcap public keys to root user..."
mkdir -p ~/.ssh/
cp ~vcap/.ssh/id_rsa* ~/.ssh/

bosh_app_dir=/var/vcap
mkdir -p ${bosh_app_dir}

# setup common folder for all folder/data
# this is what could/should be mounted as a separate persistent disk
# which is what is done for you if bosh-bootstrap creates the inception
# server for you.

store_dir=/var/vcap/store
mkdir -p ${store_dir}
chown vcap:vcap ${store_dir}

# setup common folders used by bosh-bootstrap or bosh deployments
for path in microboshes microboshes/deployments deployments releases repos stemcells inception tmp bosh_cache
do
  echo "creating /var/vcap/store/${path}"
  mkdir -p ${store_dir}/${path}
  chown vcap:vcap ${store_dir}/${path}
done

if [[ $(grep "vcap  ALL=(ALL) NOPASSWD:ALL" /etc/sudoers) == "" ]]; then
  echo "adding vcap to sudoers"
  echo "vcap  ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers
fi

echo "copying user '$ORIGUSER' authorized_keys to vcap user"
cp /home/${ORIGUSER}/.ssh/authorized_keys ${bosh_app_dir}/
cp /home/${ORIGUSER}/.ssh/authorized_keys /home/vcap/.ssh/authorized_keys
chown vcap:vcap /home/vcap/.ssh/authorized_keys
echo "copying user '$ORIGUSER' .bashrc to vcap user"
cp /home/${ORIGUSER}/.bashrc /home/vcap/
chown vcap:vcap /home/vcap/.bashrc

if [[ $(grep "export TMPDIR" /home/vcap/.bashrc) == "" ]]; then
  echo 'adding $TMPDIR to .bashrc'
  echo "export TMPDIR=/var/vcap/store/tmp" >> /home/vcap/.bashrc
fi

if [[ $(grep "export EDITOR" /home/vcap/.bashrc) == "" ]]; then
  echo 'setting $EDITOR to vim as default'
  echo "export EDITOR=vim" >> /home/vcap/.bashrc
fi

if [[ ! -h /home/vcap/.bosh_cache ]]; then
  rm -rf ~vcap/.bosh_cache/
  ln -s /var/vcap/store/bosh_cache ~vcap/.bosh_cache
fi
