#!/usr/bin/env bash

if [[ $EUID -ne 0 ]]; then
  echo "ERROR: This script must be run as root" 1>&2
  exit 1
fi

set -e # exit immediately if a simple command exits with a non-zero status

cd /var/vcap/store/repos
if [[ ! -d hub ]]; then
  git clone git://github.com/defunkt/hub.git
  cd hub
else
  cd hub
  git pull origin master
fi
rake install prefix=/usr/local

if [[ $(grep "hub alias -s" /home/vcap/.bashrc) == "" ]]; then
  echo 'adding hub alias to .bashrc'
  echo 'eval "$(hub alias -s)"' >> /home/vcap/.bashrc
fi


