#!/usr/bin/env bash

# Install BOSH CLI
#
# Options:
# * $UPGRADE - re-install or upgrade gems if already installed
# * $INSTALL_BOSH_FROM_SOURCE - install from bosh git repo

set -e # exit immediately if a simple command exits with a non-zero status

if [[ $EUID -ne 0 ]]; then
  echo "ERROR: This script must be run as root" 1>&2
  exit 1
fi

cd /var/vcap/store/inception
bundle install