#!/usr/bin/env bash

# Install BOSH CLI
#
# Options:
# * $UPGRADE - re-install or upgrade gems if already installed
# * $INSTALL_BOSH_FROM_SOURCE - install from bosh git repo

if [[ $EUID -ne 0 ]]; then
  echo "ERROR: This script must be run as root" 1>&2
  exit 1
fi

# Install a gem if $UPGRADE exists or if gem not already installed
function install_gem() {
  gem_name=$1
  if [[ ("${UPGRADE}X" != "X") || "$(gem list $gem_name | grep $gem_name)X" == "X" ]]; then
    gem install $gem_name --no-ri --no-rdoc
  else
    echo gem $gem_name already installed
  fi
}

if [[ "${INSTALL_BOSH_FROM_SOURCE}X" != "X" ]]; then
  mkdir -p /var/vcap/store/repos
  cd /var/vcap/store/repos
  git clone https://github.com/cloudfoundry/bosh.git

  bosh_dir=/var/vcap/store/repos/bosh
  cd $bosh_dir/common/
  bundle install --without=development test
  bundle exec rake install

  cd $bosh_dir/cli/
  bundle install --without=development test
  bundle exec rake install

  cd $bosh_dir/deployer/
  bundle install --without=development test
  bundle exec rake install

  cd $bosh_dir/aws_registry/
  bundle install --without=development test
  bundle exec rake install

  cd $bosh_dir/openstack_registry/
  bundle install --without=development test
  bundle exec rake install
else
  install_gem bosh_cli
  install_gem bosh_deployer
fi
