#!/usr/bin/env bash

if [[ $EUID -ne 0 ]]; then
  echo "ERROR: This script must be run as root" 1>&2
  exit 1
fi

apt-get update
apt-get install build-essential libsqlite3-dev curl rsync git-core \
  libmysqlclient-dev libxml2-dev libxslt-dev libpq-dev libsqlite3-dev \
  genisoimage mkpasswd \
  debootstrap kpartx qemu-kvm -y
