#!/usr/bin/env bash

# Install BOSH CLI
#
# Options:
# * $UPGRADE - re-install or upgrade gems if already installed
# * $INSTALL_BOSH_FROM_SOURCE - install from bosh git repo
# * $BOSH_RUBYGEM_SOURCE - URL for where bosh rubygems can be downloaded

set -e # exit immediately if a simple command exits with a non-zero status

if [[ $EUID -ne 0 ]]; then
  echo "ERROR: This script must be run as root" 1>&2
  exit 1
fi

# Install a gem if $UPGRADE exists or if gem not already installed
function install_gem() {
  gem_name=$1
  options=$2
  if [[ ("${UPGRADE}X" != "X") || "$(gem list $gem_name | grep $gem_name)X" == "X" ]]; then
    gem install $gem_name $options --no-ri --no-rdoc
  else
    echo gem $gem_name already installed
  fi
}

install_gem net-ssh '-v 2.2.2'
install_gem net-scp '-v 1.0.4'
install_gem fog '-v 1.9.0'

if [[ "${INSTALL_BOSH_FROM_SOURCE}X" != "X" ]]; then
  mkdir -p /var/vcap/store/repos
  cd /var/vcap/store/repos
  if [[ -d bosh ]]; then
    cd bosh
    git pull origin master
  else
    git clone https://github.com/cloudfoundry/bosh.git
  fi

  cd /var/vcap/store/repos/bosh
  bundle --deployment
  bundle --binstubs=/usr/local/sbin

else
  install_gem bosh_deployer
fi

if [[ ! -d /var/tmp/bosh ]]; then
  echo "Symlinking the expected stemcell creation folder into mounted volume..."
  mkdir -p /var/vcap/store/tmp/bosh
  ln -s /var/vcap/store/tmp/bosh /var/tmp/bosh
fi
