#!/usr/bin/env bash

# Install ruby 1.9.3
#
# Options:
# * $RUBY_VERSION - override ruby version to test/install
# * $UPGRADE - re-install or upgrade ruby if already installed

if [[ $EUID -ne 0 ]]; then
  echo "ERROR: This script must be run as root" 1>&2
  exit 1
fi

DISTRIB_CODENAME=lucid

if [[ "$(which ruby)" == "" || "${UPGRADE}X" != "X" || ! ("$(ruby -v)" =~ "ruby 1.9.3") ]]; then
  echo "Adding the Unboxed APT repository..."
  echo "deb http://apt.unboxedconsulting.com/ $DISTRIB_CODENAME main" > /etc/apt/sources.list.d/unboxed.list
  
  echo -e "\n Retrieving the PGP keys for the repository..."
  wget -O - http://apt.unboxedconsulting.com/release.asc | apt-key add -

  echo "Resynchronizing the package index files from their sources..."
  apt-get update

  echo -e "Installing Ruby 1.9.3...\n"
  apt-get -y install ubxd-ruby1.9.3

  echo -e "Upgrading to latest Rubygems..."
  gem update --system
else
  echo Ruby 1.9.3 already installed
fi
