#!/usr/bin/env bash

# Install BOSH CLI
#
# Options:
# * $BOSH_RUBYGEM_SOURCE - URL for where bosh rubygems can be downloaded

set -e # exit immediately if a simple command exits with a non-zero status

cd /var/vcap/store/inception
bundle install