#!/usr/bin/env bash

if [[ $EUID -ne 0 ]]; then
  echo "ERROR: This script must be run as root" 1>&2
  exit 1
fi

gem install bundler --no-ri --no-rdoc
gem pristine rake --no-ri --no-rdoc
gem install fog --no-ri --no-rdoc
