#!/usr/bin/env bash

# Install ruby 1.9.3
#
# Options:
# * $RUBY_VERSION - override ruby version to test/install
# * $UPGRADE - re-install or upgrade ruby if already installed

if [[ $EUID -ne 0 ]]; then
  echo "ERROR: This script must be run as root" 1>&2
  exit 1
fi

RUBY_VERSION=${RUBY_VERSION:-'1.9.3-p362'}

if [[ "$(which ruby)" == "" || "${UPGRADE}X" != "X" || ! ("$(ruby -v)" == "ruby 1.9.3*") ]]; then
  if [[ -d /var/vcap/store/repos/ruby-build ]]
  then
    cd /var/vcap/store/repos
    git clone git://github.com/sstephenson/ruby-build.git
    cd ruby-build
    ./install.sh
  else
    cd /var/vcap/store/repos/ruby-build
    git pull origin master
    ./install.sh
  fi
  
  rbenv-install $RUBY_VERSION
  
  rbenv rehash
  rbenv set-default $RUBY_VERSION
  ruby --version
else
  echo Ruby 1.9.3 already installed
fi
