#!/usr/bin/env bash

# Install bundler, fog, rake
#
# Options:
# * $UPGRADE - re-install or upgrade gems if already installed

if [[ $EUID -ne 0 ]]; then
  echo "ERROR: This script must be run as root" 1>&2
  exit 1
fi

# Install a gem if $UPGRADE exists or if gem not already installed
function install_gem() {
  gem_name=$1
  options=$2
  if [[ ("${UPGRADE}X" != "X") || "$(gem list $gem_name | grep $gem_name)X" == "X" ]]; then
    gem install $gem_name $options --no-ri --no-rdoc
  else
    echo gem $gem_name already installed
  fi
}

install_gem bundler --pre
install_gem rake
install_gem jazor
install_gem yaml_command
