#!/usr/bin/env bash

# Deploys a micro BOSH using "bosh micro deploy"
#
# Required:
# * $BOSH_NAME - name of bosh deployment
#   (thus /var/vcap/store/microboshes/deployments/$BOSH_NAME/micro_bosh.yml exists)
# * $MICRO_BOSH_STEMCELL_NAME - public stemcell name at
#   /var/vcap/store/stemcells/$MICRO_BOSH_STEMCELL_NAME
# * $BOSH_HOST - public IP of the deployed BOSH
# * $BOSH_USERNAME - user login to be created
# * $BOSH_PASSWORD - password for user login
# * $BOSH_UPDATED_DEPLOY - if not "" then micro BOSH already exists; so perform upgrade instead

set -e # exit immediately if a simple command exits with a non-zero status
set -u # report the usage of uninitialized variables

MICRO_BOSH_STEMCELL_PATH=/var/vcap/store/stemcells/$MICRO_BOSH_STEMCELL_NAME

# TODO in preparation for http://reviews.cloudfoundry.org/#/c/11976/
export COLUMNS=80 # force a small width for progress bar

cd /var/vcap/store/microboshes/deployments/
bosh -n micro deployment $BOSH_NAME
if [[ "${BOSH_UPDATED_DEPLOY}X" == "X" ]]; then
  echo "Performing initial deploy of micro BOSH $BOSH_NAME"
  bosh -n micro deploy $MICRO_BOSH_STEMCELL_PATH

  echo "Initially targeting micro-bosh..."
  bosh -u admin -p admin target $BOSH_HOST

  echo "Creating initial user $BOSH_USERNAME..."
  bosh login admin admin
  bosh create user $BOSH_USERNAME $BOSH_PASSWORD

  echo "Login as $BOSH_USERNAME..."
  bosh login $BOSH_USERNAME $BOSH_PASSWORD
else
  echo "Performing update deploy to micro BOSH $BOSH_NAME"
  bosh -n micro deploy $MICRO_BOSH_STEMCELL_PATH --update
fi
