#!/usr/bin/env bash

# Cleanup file permissions

if [[ $EUID -ne 0 ]]; then
  echo "ERROR: This script must be run as root" 1>&2
  exit 1
fi

chown -R vcap:vcap ~vcap/.bosh*
if [[ -d ~vcap/.gem ]]; then
  chown -R vcap:vcap ~vcap/.gem
fi
chown -R vcap:vcap /var/vcap/store/repos